@startuml
skinparam componentStyle uml2

frame "Mandatory" {
    [maven-project]
    [structs]
    [antisamy-markup-formatter]
    [workflow-step-api]
    [workflow-job]
    [workflow-cps]
    [pipeline-stage-step]
    [workflow-durable-task-step]
}

frame "Optional" {
    [matrix-project]
    [dashboard-view]
    [token-macro]
    [ant]
    [git]
}

frame "Analysis Suite" {
    [warnings-plugin] .> [analysis-core]
    [warnings-plugin] .> [analysis-model]
    [analysis-core] .>  [analysis-model]
}

[analysis-core] ..>  Mandatory
[analysis-core] ..>  Optional

@enduml